name: notes_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  serverpod_client: ^1.0.1
  serverpod_flutter: any
dev_dependencies:
  flutter_test:
    sdk: flutter
